# Generated by Django 4.1.6 on 2023-06-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0002_alter_employee_manager_department_and_more'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department_controls_projects',
            unique_together={('department', 'project')},
        ),
    ]
