# Generated by Django 4.1.6 on 2023-06-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_employee_works_for'),
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='department_app.department', unique=True),
        ),
        migrations.AlterField(
            model_name='employee_manager',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to='employee_app.employee', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'number')},
        ),
    ]
